name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  action:
    description: 'calculate or query'
    required: true
  action:
    description: 'generate versions with subcounter'
    required: false
    default: true
outputs:
  version:
    description: 'The generated or calculated version'
runs:
  using: 'node20'
  main: 'dist/index.js'


